# Intended only for simple packages
include:
  - project: "tuxedocomputers/development/installation-testing/package-build-gitlab-ci-yaml"
    ref: "next"
    file: "/build-pkg-template.yml"

build-packages:
  extends: .build-pkg-template
  variables:
    PKG_BRANCH: "main"
    SPC_ARGS: "--appstream"
    DEPLOY_SERVER_USER: deploy-deb-tuxedo-systeminfos
    DEPLOY_SERVER_RELATIVE_UPLOAD_DIR: deb/tuxedo-systeminfos/tuxedo-systeminfos
