include:
  - project: "tuxedocomputers/development/installation-testing/package-build-gitlab-ci-yaml"
    file: "/full-packaging-jobs.yml"

variables:
  BUILD_DOCKER_CONTAINER_SIZE: tiny
  BUILD_DOCKER_IMAGE_URL: registry.gitlab.com/tuxedocomputers/development/installation-testing/docker-images/deb-builder:debian-latest

  STATIC_SERVER_UPLOAD_USER: deploy-deb-fixes
  STATIC_SERVER_UPLOAD_TARGET_RELATIVE_BASE_DIR: deb/tuxedo-systeminfos/$CI_PROJECT_NAME

.test-deb-package-template:
  parallel:
    matrix:
      - test_deb_docker_image:
          - registry.gitlab.com/tuxedocomputers/development/installation-testing/docker-images/deb-builder:tuxedo-os-4-latest
